################################
# data generated by, for instance Cascades
# echo get stats from Cascades
## get any reserved nodes
# sinfo -T > ~/quick_start/ca_reserved.txt
## get queue list
# sinfo -s > ~/quick_start/ca_queues.txt
## get list of free cores
#{ for NN in $(sinfo -N -r -h -o "%N" | uniq); do sinfo -n $NN -h -o "%N %C" | cut -f 1,2 -d "/"; done; } > ~/quick_start/ca_available.txt
## get list of free gpus
# for NN in $(sinfo -N -r -h -o "%N" | uniq); do scontrol show node $NN --oneliner; done | sed 's/[,=]/\t/g' | awk 'BEGIN{ORS=""}{for(i=1; i < NF; i++){if($i~/NodeName/) {print ""$(i+1)" "};if($i~/CPUAlloc/) {print "CPUAlloc= "$(i+1)" "};if($i~/CPUTot/) {print "CPUTot= "$(i+1)" "};if($i~/gres[/]gpu/){print "available/allocated gres/gpu= " $(i+1)" "}};print "\n"}' | awk '{ if(NF==8){$0=$0"available/allocated gres/gpu= 0"};print }' > ~/quick_start/ca_available_gpu.txt
################################

suppressMessages(library(kableExtra))
suppressMessages(library(data.table))
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))

## want to create daily graph by cluster by queue

## load data
if(file.exists("all_data_combined.RDS")){
    all_data_combined <- readRDS("all_data_combined.RDS")
}

all_final <- dir(pattern="all_final")
new_data_combined <- c()
for(i in all_final){
    temp <- readRDS(i)
    new_data_combined <- rbind(new_data_combined,temp)
}
new_data_combined$date <- parse_date_time(new_data_combined$date,"dmyIMp")
new_data_combined <- mutate_at(new_data_combined,vars(metric,queue,machine),factor)

if(file.exists("all_data_combined.RDS")){
    all_data_combined <- rbind(all_data_combined,new_data_combined)
}else{
    all_data_combined <- new_data_combined
}
#### for ease, start with %utilization graph, all on same scale, can play with others later
utilization_data <- filter(all_data_combined,grepl("/",all_data_combined$value),metric=="%utilization cores/nodes") %>%
    separate(value,into=c("cores","nodes"),sep="/") %>%
    pivot_longer(cols=cores:nodes,names_to="unit",values_to="utilization") %>%
    mutate_at(vars(utilization),as.integer)

## lets do today, week to date, month to date, year to date


this_month <- month(Sys.Date())
this_year <- year(Sys.Date())

gg2_today <- ggplot(utilization_data %>% filter(format(utilization_data$date,"%F")==format(today(),"%F")),
			aes(x=date,y=utilization,color=queue,linetype=unit)) +
    geom_line() +
    ylab(paste0("Utilization today, ",format(today(),"%B %d"))) + 
    xlab("") +
    facet_grid(rows="machine", scales="free_y") +
    scale_x_datetime(date_labels = "%k:%M", date_breaks='2 hour',date_minor_breaks='1 hour',
    sec.axis=dup_axis(labels = scales::time_format("%I %p"))) +
    theme_bw() +
    theme(axis.text.x = element_text(angle=90,vjust=0.5))

gg2_month <- ggplot(utilization_data %>% filter(month(utilization_data$date)==this_month),
                    aes(x=date,y=utilization,color=queue,linetype=unit)) +
    geom_line() +
    ylab(paste0(month(this_month,abbr = FALSE, label=TRUE)," utilization")) +
    xlab("") +
    facet_grid(rows="machine", scales="free_y") +
    scale_x_datetime(date_labels = "%a -- %d", date_breaks='1 day',date_minor_breaks='12 hour') +
    theme_bw() +
    theme(axis.text.x = element_text(angle=90, vjust=0.5))

gg2_year <- ggplot(utilization_data %>% filter(year(utilization_data$date)==this_year),
                   aes(x=date,y=utilization,color=queue,linetype=unit)) +
    geom_line() +
    ylab("utilization year to date") + 
    xlab("") +
    facet_grid(rows="machine",scales="free_y") +
    scale_x_datetime(date_labels = "%b-%d -- %U", date_breaks='1 week',date_minor_breaks='1 day') +
    theme_bw() +
    theme(axis.text.x = element_text(angle=90, vjust=0.5))


#### save combined data
#### will play with this later to segregate by some time period, month? quarter? year?
saveRDS(all_data_combined,"all_data_combined.RDS")
ggsave("all_data_combined_today.jpg",gg2_today)
ggsave("all_data_combined_month.jpg",gg2_month)
ggsave("all_data_combined_year.jpg",gg2_year)

#### delete old data
for(i in all_final){
    file.remove(i)
}




